name: Innixstall
description: Innixstall

runs:
  using: composite
  steps:
    - name: chehck for nix
      id: check-nix
      shell: bash
      run: |
        if command -v nix &> /dev/null
        then
          echo "nix-found=true" | tee -a $GITHUB_OUTPUT
        else
          echo "nix-found=false" | tee -a $GITHUB_OUTPUT
        fi
    - name: Install nix
      if: ${{steps.check-nix.nix-found != 'true' }}
      uses: nixbuild/nix-quick-install-action@v29
