name: Build Tarball

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  tar:
    name: Tarball
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

